### PR TITLE
[do not merge] Rebased 001e6c7

### PR DESCRIPTION
**Pull request by misberner**

### CODE REVIEW

**Comment by misberner** [comment]
This is being tested here: https://github.com/stackrox/stackrox/pull/3255

**Review by porridge — APPROVED** [review]
LGTM

**Review by janisz — APPROVED** [review]
There is a conflict on go.mod

**Comment by misberner** [comment]
Right, the conflict doesn't matter because this will be force-pushed. It is a straight-up rebase of our changes, preserving linear history.

I'm holding off on force-pushing to `main` because this causes a bump in K8s deps to v0.24.x, which is currently failing in `rox`: https://github.com/stackrox/stackrox/pull/3255

**Comment by misberner** [comment]
This has been promoted to the new `main` branch. The old state of `main` has be preserved as branch [`main-backup-2022-10-05`](https://github.com/stackrox/helm-operator/tree/main-backup-2022-10-05).

**Pull request merged**
