### PR TITLE
Bump k8s deps to v0.24.6

### PR DESCRIPTION
**Pull request by misberner**
Also bumps the Helm dep to a non-vulnerable version

### CODE REVIEW

**Review by porridge — COMMENTED** [review]
Perhaps it would be better to rebase our changes instead?
[Upstream](https://github.com/operator-framework/helm-operator-plugins/commit/c75c4f129d5ea2887621891e29e975d490f7ddf8) seems to have already done this, and some of their changes are different to what you did :thinking:

**Comment by misberner** [comment]
Good point, rebased: https://github.com/stackrox/helm-operator/pull/32 (I dropped my memory leak fix from our branch because it already is upstream).

What's the process for rebasing, just hard set our `main` ref to the HEAD of the `rebased-` branch and then force push? Or just leave the `rebased-` branch and set it as the default in GitHub?

Btw, if you're referring to the kubeclock fix, I would say that my fix is what is actually required here. I can try to upstream it.

**Comment by misberner** [comment]
https://github.com/operator-framework/helm-operator-plugins/pull/199

**Comment by porridge** [comment]
> hard set our `main` ref to the HEAD of the `rebased-` branch and then force push

:point_up: this one

But before doing so please also create a `main-backup-<date>` tag at the current tip of `main` just in case.

And you'll need to temporarily disable branch protection in settings to do the force-push.

**Comment by misberner** [comment]
Superseded by https://github.com/stackrox/helm-operator/pull/32

**Pull request closed without merging**
